#ifndef __LFRL_OGL_CAPACITIES_FUNC_TYPE_GUARD__
#define __LFRL_OGL_CAPACITIES_FUNC_TYPE_GUARD__

#include "../internal/namespace_macros.h"

BEGIN_LFRL_OGL_CAPACITIES_NAMESPACE

enum struct FuncType
{
	NEVER = GL_NEVER,
	LESS_THAN = GL_LESS,
	EQUAL_TO = GL_EQUAL,
	LESS_THAN_OR_EQUAL_TO = GL_LEQUAL,
	GREATER_THAN = GL_GREATER,
	NOT_EQUAL_TO = GL_NOTEQUAL,
	GREATER_THAN_OR_EQUAL_TO = GL_GEQUAL,
	ALWAYS = GL_ALWAYS
};

END_LFRL_OGL_CAPACITIES_NAMESPACE

#endif
